import React, { useState, useEffect } from 'react';
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { 
  PatientData, 
  NerveReading, 
  NerveType, 
  AnalysisResult
} from './types';
import { DEFAULT_REFERENCES, TEXTS } from './constants';
import { runFullAnalysis } from './utils/analysis';
import { getClinicalSummary } from './services/geminiService';

const App: React.FC = () => {
  const [lang, setLang] = useState<'es' | 'en'>('es');
  const t = TEXTS[lang]; // Shortcut for translations

  const [patient, setPatient] = useState<PatientData>({ 
    age: 45, 
    height: 170
  });
  const [readings, setReadings] = useState<NerveReading[]>([]);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [activeAccordion, setActiveAccordion] = useState<string | null>(null);
  
  const [aiSummary, setAiSummary] = useState<string>('');
  const [isAiLoading, setIsAiLoading] = useState(false);

  useEffect(() => {
    const initialReadings: NerveReading[] = DEFAULT_REFERENCES.map(ref => ({
      nerveName: ref.nerveName,
      type: ref.type,
      distalLatency: 0,
      peakLatency: 0,
      amplitude: 0,
      velocity: 0
    }));
    setReadings(initialReadings);
  }, []);

  useEffect(() => {
    if (result) {
      setResult(null);
      setAiSummary('');
    }
  }, [patient, readings, lang]); // Reset if lang changes to update text in result

  const handlePatientChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setPatient(prev => ({ 
      ...prev, 
      [name]: Number(value) 
    }));
  };

  const handleReadingChange = (index: number, field: keyof NerveReading, value: string) => {
    const newReadings = [...readings];
    const upperValue = value.trim().toUpperCase();
    
    if (upperValue === 'NR' || upperValue === 'N') {
      newReadings[index] = { ...newReadings[index], [field]: upperValue };
    } else if (value === '') {
      newReadings[index] = { ...newReadings[index], [field]: '' };
    } else {
      const sanitized = value.replace(',', '.');
      if (/^-?\d*\.?\d*$/.test(sanitized)) {
        newReadings[index] = { ...newReadings[index], [field]: sanitized };
      }
    }
    setReadings(newReadings);
  };

  const handleCalculate = () => {
    setIsLoading(true);
    setAiSummary(''); 
    setTimeout(() => {
      const analysis = runFullAnalysis(readings, patient, lang);
      setResult(analysis);
      setIsLoading(false);
    }, 500);
  };

  const handleGenerateAiSummary = async () => {
    if (!result) return;
    setIsAiLoading(true);
    const summary = await getClinicalSummary(patient, readings, result);
    setAiSummary(summary);
    setIsAiLoading(false);
  };

  const handleDownloadReport = () => {
    if (!result) return;

    const report = `
${t.title.toUpperCase()} - REPORT
==========================================================
Date: ${new Date().toLocaleDateString()}

${t.patientInfo.toUpperCase()}:
------------------
${t.age}: ${patient.age}
${t.height}: ${patient.height}

${t.readingsTitle.toUpperCase()}:
----------------------------------
${readings.map(r => `
${r.nerveName} (${r.type})
  - ${t.ampHeader}: ${r.amplitude}
  - ${r.nerveName.includes('Sural') ? 'Latency' : 'Velocity'}: ${r.nerveName.includes('Sural') ? r.peakLatency : r.velocity}
`).join('')}

SCORES:
-------------------
${t.score2Title.toUpperCase()}: ${result.score2.total} / 8 PTS
${result.score2.interpretationBody}
${result.score2.details.map(d => `  - ${d.nerve}: ${d.value} (P${(d.percentile * 100).toFixed(1)}) -> ${d.points} pt`).join('\n')}

${t.score4Title.toUpperCase()}: ${result.score4.total} / 8 PTS (${t.severity}: ${result.score4.severityLabel})
${result.score4.details.map(d => `  - ${d.nerve}: ${d.value} (P${(d.percentile * 100).toFixed(1)}) -> ${d.points} pt`).join('\n')}

${t.finalClass.toUpperCase()}:
---------------------------------
${result.score2.interpretationBody}
${t.severity}: ${result.score4.severityLabel}

${t.aiAssistant.toUpperCase()}:
-------------------------------------
${aiSummary || 'Not generated.'}

==========================================================
Generated by Polineuropathy-Assistant Electrodiagnóstico PMR Specialist Platform by Leo J Escobar.
`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Report_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleGeneratePDF = () => {
    if (!result) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    // A4 height is ~297mm. Goal: Fit everything in one page.

    // --- Compact Header (30mm) ---
    doc.setFillColor(30, 58, 138); // blue-900 like color (Medical Blue)
    doc.rect(0, 0, pageWidth, 30, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Polineuropathy-Assistant PMR", 14, 12);
    
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(191, 219, 254); // blue-200
    doc.text(t.subtitle, 14, 19);
    
    doc.text(new Date().toLocaleDateString(), pageWidth - 14, 12, { align: "right" });

    // --- Patient Info (Single Line Compact) ---
    let finalY = 38;
    doc.setTextColor(51, 65, 85); // slate-700
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(`${t.patientInfo.toUpperCase()}:`, 14, finalY);
    
    doc.setFont("helvetica", "normal");
    doc.text(`${t.age}: ${patient.age}   |   ${t.height}: ${patient.height} cm`, 75, finalY);

    // --- Table of Readings (Compact) ---
    finalY += 6;
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(t.readingsTitle.toUpperCase(), 14, finalY);

    const tableData = readings.map(r => {
        const isSural = r.nerveName.includes('Sural');
        return [
            r.nerveName,
            r.type,
            isSural ? (r.peakLatency || '-') : (r.velocity || '-'),
            r.amplitude || '-'
        ];
    });

    autoTable(doc, {
        startY: finalY + 2,
        head: [[t.nerveHeader, 'Tipo', t.paramHeader, t.ampHeader]],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [241, 245, 249], textColor: [71, 85, 105], fontSize: 8, fontStyle: 'bold', minCellHeight: 6 },
        bodyStyles: { fontSize: 8, textColor: [51, 65, 85], minCellHeight: 6 },
        styles: { cellPadding: 1.5 },
    });

    // @ts-ignore
    finalY = doc.lastAutoTable.finalY + 8;

    // --- Results Box (Compact) ---
    const isAbnormal = result.score2.isAbnormal;
    const boxColor = isAbnormal ? [220, 38, 38] : [22, 163, 74]; 
    const boxHeight = isAbnormal ? 30 : 25;
    
    doc.setFillColor(isAbnormal ? 254 : 240, isAbnormal ? 242 : 253, isAbnormal ? 242 : 244); 
    doc.setDrawColor(boxColor[0], boxColor[1], boxColor[2]);
    doc.setLineWidth(0.5);
    doc.roundedRect(14, finalY, pageWidth - 28, boxHeight, 2, 2, 'FD');
    
    doc.setFillColor(boxColor[0], boxColor[1], boxColor[2]);
    doc.rect(14, finalY, 2, boxHeight, 'F');

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139); 
    doc.text(t.finalClass.toUpperCase(), 20, finalY + 6);

    doc.setFontSize(11);
    doc.setTextColor(boxColor[0], boxColor[1], boxColor[2]); 
    const splitTitle = doc.splitTextToSize(result.score2.interpretationBody, pageWidth - 45);
    doc.text(splitTitle, 20, finalY + 13);

    if (isAbnormal) {
         doc.setFontSize(10);
         doc.setTextColor(51, 65, 85);
         doc.text(`${t.severity}: ${result.score4.severityLabel}`, 20, finalY + boxHeight - 5);
    }

    finalY += boxHeight + 8;

    // --- Scores Detail Tables (Side by Side) ---
    
    const startYScores = finalY;
    const halfWidth = (pageWidth - 34) / 2; // 14 margin left, 14 margin right, 6 gap

    // Left Table: Score 2
    doc.setFontSize(9);
    doc.setTextColor(51, 65, 85);
    doc.setFont("helvetica", "bold");
    doc.text(`${t.score2Title} (${result.score2.total}/8)`, 14, startYScores);

    // Right Table: Score 4
    doc.text(`${t.score4Title} (${result.score4.total}/8)`, 14 + halfWidth + 6, startYScores);

    // Prepare data (shorten strings for compact table)
    const score2Rows = result.score2.details.map(d => [
        d.nerve.replace(' (Motor)', '').replace(' (Sensitivo)', '').replace(' (Latencia)', ''),
        d.value === 'NR' ? 'NR' : d.value,
        d.value === 'NR' ? '-' : `P${(d.percentile * 100).toFixed(0)}`,
        d.points
    ]);

    const score4Rows = result.score4.details.map(d => [
        d.nerve.replace(' (Motor)', '').replace(' (Sensitivo)', ''),
        d.value === 'NR' ? 'NR' : d.value,
        d.value === 'NR' ? '-' : `P${(d.percentile * 100).toFixed(0)}`,
        d.points
    ]);

    // Render Left Table
    autoTable(doc, {
        startY: startYScores + 2,
        head: [['Nervio', 'Val', '%', 'Pt']],
        body: score2Rows,
        theme: 'striped',
        headStyles: { fillColor: [51, 65, 85], fontSize: 7, minCellHeight: 5, halign: 'center' },
        bodyStyles: { fontSize: 7, minCellHeight: 5, halign: 'center' },
        columnStyles: { 0: { halign: 'left' } },
        styles: { cellPadding: 1, overflow: 'ellipsize' },
        margin: { left: 14 },
        tableWidth: halfWidth
    });

    // @ts-ignore
    const finalYScore2 = doc.lastAutoTable.finalY;

    // Render Right Table
    autoTable(doc, {
        startY: startYScores + 2,
        head: [['Nervio', 'Val', '%', 'Pt']],
        body: score4Rows,
        theme: 'striped',
        headStyles: { fillColor: [51, 65, 85], fontSize: 7, minCellHeight: 5, halign: 'center' },
        bodyStyles: { fontSize: 7, minCellHeight: 5, halign: 'center' },
        columnStyles: { 0: { halign: 'left' } },
        styles: { cellPadding: 1, overflow: 'ellipsize' },
        margin: { left: 14 + halfWidth + 6 },
        tableWidth: halfWidth
    });

    // @ts-ignore
    const finalYScore4 = doc.lastAutoTable.finalY;
    
    // Resume Y after the tallest table
    finalY = Math.max(finalYScore2, finalYScore4) + 8;

    // --- AI Summary ---
    if (aiSummary) {
        // Estimate height for AI box (approx 35mm)
        const aiBoxHeight = 35; 
        
        doc.setFillColor(245, 247, 255); // Indigo 50
        doc.roundedRect(14, finalY, pageWidth - 28, aiBoxHeight, 2, 2, 'F');
        
        doc.setFont("helvetica", "bold");
        doc.setTextColor(79, 70, 229); // Indigo 600
        doc.setFontSize(9);
        doc.text(t.aiAssistant.toUpperCase(), 18, finalY + 6);
        
        doc.setFont("helvetica", "normal");
        doc.setTextColor(51, 65, 85);
        doc.setFontSize(8);
        
        const splitSummary = doc.splitTextToSize(aiSummary, pageWidth - 36);
        doc.text(splitSummary, 18, finalY + 11);
    }

    // Footer
    doc.setFontSize(7);
    doc.setTextColor(148, 163, 184);
    doc.text(`Generated by Polineuropathy-Assistant Electrodiagnóstico PMR by Leo J Escobar`, pageWidth / 2, 290, { align: "center" });

    doc.save(`Report_PM&R_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const toggleAccordion = (id: string) => {
    setActiveAccordion(activeAccordion === id ? null : id);
  };

  return (
    <div className="min-h-screen bg-slate-50 p-4 md:p-8 print:p-0">
      
      {/* Banner removed based on user request */}

      <header className="max-w-6xl mx-auto mb-8 flex flex-col md:flex-row items-start md:items-center justify-between border-b border-slate-200 pb-6 gap-4 print:mb-4">
        <div>
          <h1 className="text-3xl font-black text-slate-900 tracking-tight">Polineuropathy-Assistant <span className="text-blue-600">Electrodiagnóstico PMR</span></h1>
          <p className="text-slate-600 font-medium text-sm mt-1">{t.subtitle}</p>
        </div>
        <div className="flex flex-col items-end gap-2">
           <button 
             onClick={() => setLang(prev => prev === 'es' ? 'en' : 'es')}
             className="px-3 py-1 bg-slate-200 hover:bg-slate-300 rounded text-xs font-bold text-slate-700 transition print:hidden"
           >
             {lang === 'es' ? '🇺🇸 English' : '🇪🇸 Español'}
           </button>
           <div className="text-right hidden md:block print:block">
            <p className="text-xs font-bold text-slate-400">{t.professionalTool}</p>
            <p className="text-xs text-slate-500">{t.basedOn}</p>
            <p className="text-[9px] text-slate-300 mt-1 hidden print:block italic">{new Date().toLocaleDateString()}</p>
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-8">
        <div className="lg:col-span-4 space-y-6 print:hidden">
          <section className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
            <h2 className="text-sm font-bold text-slate-800 uppercase mb-4 flex items-center gap-2">
              <div className="w-1.5 h-4 bg-blue-600 rounded-full"></div>
              {t.patientInfo}
            </h2>
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-[10px] font-bold text-slate-400 uppercase mb-1">{t.age}</label>
                  <input type="number" inputMode="decimal" name="age" value={patient.age} onChange={handlePatientChange} className="w-full bg-slate-50 border border-slate-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 outline-none" />
                </div>
                <div>
                  <label className="block text-[10px] font-bold text-slate-400 uppercase mb-1">{t.height}</label>
                  <input type="number" inputMode="decimal" name="height" value={patient.height} onChange={handlePatientChange} className="w-full bg-slate-50 border border-slate-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 outline-none" />
                </div>
              </div>
            </div>
          </section>

          <button onClick={handleCalculate} disabled={isLoading} className="w-full bg-blue-700 text-white font-bold py-4 rounded-2xl shadow-xl hover:bg-blue-800 transition transform hover:-translate-y-1 active:scale-95 flex items-center justify-center gap-2 disabled:opacity-50">
            {isLoading ? t.processing : t.calculateBtn}
          </button>
        </div>

        <div className="lg:col-span-8 space-y-6 print:col-span-12">
          <section className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden print:border-none print:shadow-none">
            <h2 className="hidden print:block text-xs font-bold text-slate-500 uppercase px-6 pt-4 mb-2">{t.readingsTitle}</h2>
            <table className="w-full text-left">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200">
                  <th className="px-6 py-4 text-[10px] font-black text-slate-500 uppercase tracking-widest">{t.nerveHeader}</th>
                  <th className="px-6 py-4 text-[10px] font-black text-slate-500 uppercase tracking-widest text-center">{t.paramHeader}</th>
                  <th className="px-6 py-4 text-[10px] font-black text-slate-500 uppercase tracking-widest text-center">{t.ampHeader}</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {readings.map((r, idx) => {
                  const isSural = r.nerveName.includes('Sural');
                  const mainValue = isSural ? r.peakLatency : r.velocity;
                  
                  return (
                    <tr key={idx} className="hover:bg-slate-50/50">
                      <td className="px-6 py-4">
                        <div className="font-bold text-slate-700">{r.nerveName}</div>
                        <div className="text-[9px] text-slate-400 font-bold uppercase">{r.type}</div>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex flex-col items-center">
                          <label className="text-[9px] text-slate-400 font-bold mb-1 print:hidden">{isSural ? t.latency : t.velocity}</label>
                          <input 
                            type="text" 
                            inputMode="decimal"
                            value={mainValue === 0 ? '' : mainValue} 
                            onChange={(e) => handleReadingChange(idx, isSural ? 'peakLatency' : 'velocity', e.target.value)} 
                            placeholder="0.0 o NR"
                            className="w-20 bg-slate-50 border border-slate-200 rounded px-2 py-1 text-center text-sm font-medium focus:ring-1 focus:ring-blue-500 outline-none uppercase print:bg-white print:border-none" 
                          />
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex flex-col items-center">
                          <label className="text-[9px] text-slate-400 font-bold mb-1 print:hidden">
                            {isSural ? t.ampHeaderSural.toUpperCase() : t.ampHeader.toUpperCase()} ({isSural ? t.ampUnitSural : t.ampUnitMotor})
                          </label>
                          <input 
                            type="text" 
                            inputMode="decimal"
                            value={r.amplitude === 0 ? '' : r.amplitude} 
                            onChange={(e) => handleReadingChange(idx, 'amplitude', e.target.value)} 
                            placeholder="0.0 o NR"
                            className="w-20 bg-slate-50 border border-slate-200 rounded px-2 py-1 text-center text-sm font-medium focus:ring-1 focus:ring-blue-500 outline-none uppercase print:bg-white print:border-none" 
                          />
                        </div>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </section>

          {result && (
            <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
              <div className="bg-blue-900 text-white p-6 md:p-8 rounded-3xl shadow-2xl relative overflow-hidden print:bg-slate-50 print:text-slate-900 print:shadow-none print:border print:border-slate-200 print:p-6">
                
                {/* Decoration removed for cleaner medical look */}

                {/* Header Row with Buttons */}
                <div className="relative z-20 flex justify-between items-start mb-4">
                  <h2 className="text-blue-200 text-[10px] font-black uppercase tracking-[0.2em] print:text-slate-500 pt-1">
                    {t.finalClass}
                  </h2>
                  <div className="flex gap-2 print:hidden">
                      <button 
                        onClick={handleDownloadReport}
                        className="bg-white/10 hover:bg-white/20 text-white px-3 py-2 rounded-lg transition cursor-pointer flex items-center gap-2"
                        title={t.downloadTxt}
                      >
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
                        <span className="text-xs font-bold">TXT</span>
                      </button>

                      <button 
                        onClick={handleGeneratePDF}
                        className="bg-white/10 hover:bg-white/20 text-white px-3 py-2 rounded-lg transition cursor-pointer flex items-center gap-2"
                        title="Generar PDF"
                      >
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
                        <span className="text-xs font-bold">PDF</span>
                      </button>

                      <button 
                        onClick={() => window.print()}
                        className="bg-white/10 hover:bg-white/20 text-white px-3 py-2 rounded-lg transition cursor-pointer"
                        title={t.printReport}
                      >
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
                      </button>
                  </div>
                </div>
                
                <div className="relative z-10 space-y-4">
                   {/* Score 2 Interpretation */}
                   <div>
                      <p className={`text-xl md:text-2xl font-black leading-tight ${result.score2.isAbnormal ? 'text-red-300 print:text-red-700' : 'text-green-300 print:text-green-700'}`}>
                        {result.score2.interpretationBody}
                      </p>
                   </div>

                   {/* Score 4 Interpretation (Severity) - Solo visible si hay anomalía (Score 2 >= 2) */}
                   {result.score2.isAbnormal && (
                      <div className="mt-2">
                        <p className="text-lg md:text-xl font-bold text-white print:text-slate-900 uppercase tracking-wide">
                          {t.severity}: <span className={
                            result.score4.total >= 6 ? 'text-red-400 print:text-red-700' : 
                            result.score4.total >= 3 ? 'text-orange-300 print:text-orange-700' : 
                            result.score4.total >= 1 ? 'text-yellow-300 print:text-yellow-700' : 
                            'text-slate-300 print:text-slate-500'
                          }>{result.score4.severityLabel}</span>
                        </p>
                      </div>
                   )}
                </div>
              </div>

              {/* Seccion Detalles de Scores (White Boxes) */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm print:p-4 relative overflow-hidden">
                  <div className={`absolute top-0 left-0 w-1 h-full ${result.score2.isAbnormal ? 'bg-red-500' : 'bg-green-500'}`}></div>
                  <div className="flex justify-between items-center mb-4">
                    <h3 className="font-black text-slate-800 uppercase text-xs tracking-widest">Detalle {t.score2Title}</h3>
                    <div className={`px-2 py-1 rounded-md text-sm font-black ${result.score2.isAbnormal ? 'bg-red-50 text-red-600' : 'bg-green-50 text-green-600'}`}>
                      {result.score2.total} / 8 {t.points}
                    </div>
                  </div>
                  <div className="space-y-3">
                    {result.score2.details.map((d, i) => (
                      <div key={i} className="flex justify-between items-center text-xs p-2 bg-slate-50 rounded-lg">
                        <span className="font-medium text-slate-600">{d.nerve}</span>
                        <div className="flex items-center gap-3">
                          <span className="text-slate-400 font-bold">{d.value === 'NR' ? 'NR' : `P${(d.percentile * 100).toFixed(1)}`}</span>
                          <span className={`font-black ${d.points > 0 ? 'text-red-500' : 'text-slate-400'}`}>{d.points} pt</span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm print:p-4 relative overflow-hidden">
                  <div className={`absolute top-0 left-0 w-1 h-full ${result.score4.isAbnormal ? 'bg-red-500' : 'bg-green-500'}`}></div>
                  <div className="flex justify-between items-center mb-4">
                    <h3 className="font-black text-slate-800 uppercase text-xs tracking-widest">Detalle {t.score4Title}</h3>
                    <div className={`px-2 py-1 rounded-md text-sm font-black ${result.score4.isAbnormal ? 'bg-red-50 text-red-600' : 'bg-green-50 text-green-600'}`}>
                      {result.score4.total} / 8 {t.points}
                    </div>
                  </div>
                  <div className="space-y-3">
                    {result.score4.details.map((d, i) => (
                      <div key={i} className="flex justify-between items-center text-xs p-2 bg-slate-50 rounded-lg">
                        <span className="font-medium text-slate-600">{d.nerve}</span>
                        <div className="flex items-center gap-3">
                          <span className="text-slate-400 font-bold">{d.value === 'NR' ? 'NR' : `P${(d.percentile * 100).toFixed(1)}`}</span>
                          <span className={`font-black ${d.points > 0 ? 'text-red-500' : 'text-slate-400'}`}>{d.points} pt</span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* Sección IA */}
              <div className="bg-gradient-to-br from-indigo-50 to-blue-50 p-6 rounded-2xl border border-blue-100 shadow-sm print:bg-white print:border-slate-200">
                 <div className="flex justify-between items-start mb-4">
                    <h3 className="font-black text-slate-800 uppercase text-xs tracking-widest flex items-center gap-2">
                       <svg className="w-4 h-4 text-indigo-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
                       {t.aiAssistant}
                    </h3>
                 </div>
                 
                 {aiSummary ? (
                   <div className="prose prose-sm max-w-none">
                     <div className="text-sm text-slate-700 leading-relaxed whitespace-pre-line">{aiSummary}</div>
                     <button 
                        onClick={() => setAiSummary('')}
                        className="mt-4 text-[10px] font-bold text-slate-400 hover:text-slate-600 uppercase print:hidden"
                     >
                        {t.aiRegen}
                     </button>
                   </div>
                 ) : (
                   <div className="text-center py-6 print:hidden">
                     <p className="text-xs text-slate-500 mb-4">{t.aiPrompt}</p>
                     <button 
                       onClick={handleGenerateAiSummary}
                       disabled={isAiLoading}
                       className="bg-indigo-600 hover:bg-indigo-500 text-white px-5 py-2.5 rounded-xl text-xs font-bold transition flex items-center justify-center gap-2 mx-auto disabled:opacity-50"
                     >
                       {isAiLoading ? (
                         <>
                           <svg className="animate-spin h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
                           {t.processing}
                         </>
                       ) : (
                         <>
                           <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg>
                           {t.aiBtn}
                         </>
                       )}
                     </button>
                   </div>
                 )}
              </div>
            </div>
          )}
        </div>
      </main>

      <section className="max-w-6xl mx-auto mt-12 space-y-4 print:hidden">
        <div className="bg-white rounded-xl border border-slate-200 overflow-hidden shadow-sm">
          <button onClick={() => toggleAccordion('usage')} className="w-full flex items-center justify-between p-4 hover:bg-slate-50 transition text-left">
            <span className="font-bold text-slate-700 text-sm flex items-center gap-2">
              <svg className="w-4 h-4 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
              {t.whenToUse}
            </span>
            <svg className={`w-5 h-5 transition-transform ${activeAccordion === 'usage' ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7"/></svg>
          </button>
          {activeAccordion === 'usage' && (
            <div className="p-4 border-t border-slate-100 bg-slate-50 text-xs text-slate-600 leading-relaxed">
              {t.whenToUseText}
            </div>
          )}
        </div>

        <div className="bg-white rounded-xl border border-slate-200 overflow-hidden shadow-sm">
          <button onClick={() => toggleAccordion('references')} className="w-full flex items-center justify-between p-4 hover:bg-slate-50 transition text-left">
            <span className="font-bold text-slate-700 text-sm flex items-center gap-2">
              <svg className="w-4 h-4 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"/></svg>
              {t.references}
            </span>
            <svg className={`w-5 h-5 transition-transform ${activeAccordion === 'references' ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7"/></svg>
          </button>
          {activeAccordion === 'references' && (
            <div className="p-4 border-t border-slate-100 bg-slate-50 text-xs text-slate-600 leading-relaxed space-y-3">
              <p>1. Dyck, P. J. , Kratz, K. M. , Lehman, K. A. , Karnes, J. L. , Melton, L. J. , O'Brien, P. C. , Litchy, W. J. , Windebank, A. J. , Smith, B. E. , Low, P. A. , Service, F. J. , Rizza, R. A. & Zimmerman, B. R. (1991). The Rochester Diabetic Neuropathy Study. Neurology, 41 (6), 799-807.</p>
              <p>2. Kumbhare D, Robinson L, Buschbacher R. Buschbacher’s manual of nerve conduction studies. 3rd ed. New York: Springer Publishing Company; 2015. 1 p.</p>
              <p>3. Davies JL, Lodermeier KA, Klein DM, Carter RE, Dyck PJB, Litchy WJ, Dyck PJ. Composite nerve conduction scores and signs for diagnosis and somatic staging of diabetic polyneuropathy: Mid North American ethnic cohort survey. Muscle Nerve. 2023 Jul;68(1):29-38. doi: 10.1002/mus.27793. Epub 2023 Mar 1. PMID: 36734298; PMCID: PMC10272036.</p>
              <p>4. Buschbacher RM. Tibial nerve motor conduction to the abductor hallucis. Am J Phys Med Rehabil. 1999 Nov-Dec;78(6 Suppl):S15-20. doi: 10.1097/00002060-199911001-00004. PMID: 10573092.</p>
              <p>5. Buschbacher RM. Peroneal nerve motor conduction to the extensor digitorum brevis. Am J Phys Med Rehabil. 1999 Nov-Dec;78(6 Suppl):S26-31. doi: 10.1097/00002060-199911001-00006. PMID: 10573094.</p>
              <p>6. Buschbacher RM. Ulnar nerve motor conduction to the abductor digiti minimi. Am J Phys Med Rehabil. 1999 Nov-Dec;78(6 Suppl):S9-14. doi: 10.1097/00002060-199911001-00003. PMID: 10573091.</p>
            </div>
          )}
        </div>

        <div className="bg-white rounded-xl border border-slate-200 overflow-hidden shadow-sm">
          <button onClick={() => toggleAccordion('development')} className="w-full flex items-center justify-between p-4 hover:bg-slate-50 transition text-left">
            <span className="font-bold text-slate-700 text-sm flex items-center gap-2">
              <svg className="w-4 h-4 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.618.309a6 6 0 01-3.411.454l-2.387-.477a2 2 0 00-1.022.547l-1.157 1.157a2 2 0 00-.547 1.022l-.477 2.387a2 2 0 00.547 1.022l1.157 1.157a2 2 0 001.022.547l2.387.477a6 6 0 003.411-.454l.618-.309a6 6 0 013.86-.517l2.387.477a2 2 0 001.022-.547l1.157-1.157a2 2 0 00.547-1.022l.477-2.387a2 2 0 00-.547-1.022l-1.157-1.157zM12 13V4M7 8.5L12 3l5 5.5"/></svg>
              {t.development}
            </span>
            <svg className={`w-5 h-5 transition-transform ${activeAccordion === 'development' ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7"/></svg>
          </button>
          {activeAccordion === 'development' && (
            <div className="p-4 border-t border-slate-100 bg-slate-50 text-xs text-slate-600 leading-relaxed space-y-2">
              <p>{t.developmentText1}</p>
              <p>{t.developmentText2}</p>
              <p>{t.developmentText3}</p>
              <p className="font-bold italic">{t.developmentText4}</p>
            </div>
          )}
        </div>
      </section>

      <footer className="max-w-6xl mx-auto mt-12 py-8 border-t border-slate-200 text-center print:hidden">
        <p className="text-slate-400 text-[10px] font-bold uppercase tracking-widest">{t.footer}</p>
      </footer>
    </div>
  );
};

export default App;